---
title: "load_data"
author: "Franklin Yang, Genevieve Lyons, Rachel Ketchum"
date: "11/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Run this Rmd file to refresh the database
Install packages
```{r}
# install.packages('RSQLite')
```

Load data into sqlite
```{r}
rm(list=ls())
library(DBI)
# for testing
# con <- dbConnect(RSQLite::SQLite(), ":memory:")

con <- dbConnect(RSQLite::SQLite(), "./database/db.sqlite")

### Load Hospital Info
  #Pull Data
hospital_info <- read.csv(file="../data/hospital_general_information.csv", header=TRUE, sep=",", 
                          colClasses = rep("character", 29))
  #replace .'s with _s
names(hospital_info) <- gsub("\\.", "_", names(hospital_info))


# spending by claim
spending_by_claim <- read.csv(file="../data/claims/medicare_hospital_spending_by_claim.csv", header=TRUE, sep=",",
                              colClasses = c("character", "character", "character", "factor", "factor", "numeric", "numeric", "numeric", "factor", "factor", "factor", "factor", "factor"))
  #Clean %'s
spending_by_claim$Percent.of.Spending.Hospital <- as.numeric(gsub("%", "", spending_by_claim$Percent.of.Spending.Hospital))
spending_by_claim$Percent.of.Spending.State <- as.numeric(gsub("%", "", spending_by_claim$Percent.of.Spending.State))
spending_by_claim$Percent.of.Spending.Nation <- as.numeric(gsub("%", "", spending_by_claim$Percent.of.Spending.Nation))
  #replace .'s with _s
names(spending_by_claim) <- gsub("\\.", "_", names(spending_by_claim))

# spending by beneficiary
spending_by_beneficiary <- read.csv(file="../data/claims/medicare_spending_per_beneficiary___hospital.csv", header=TRUE, sep=",",
                                    colClasses = c("character", "character", "character", "character", "character", "character", "character", "character", "factor", "factor", "factor", "factor", "factor", "factor", "factor"))
  #Clean spending field
spending_by_beneficiary$Score <- as.numeric(ifelse(spending_by_beneficiary$Score == "Not Available", NA, spending_by_beneficiary$Score))
  #replace .'s with _s
names(spending_by_beneficiary) <- gsub("\\.", "_", names(spending_by_beneficiary))

# outcomes tables
# https://data.medicare.gov/Hospital-Compare/Hospital-Value-Based-Purchasing-HVBP-Total-Perform/ypbt-wvdk
outcomes_performance_scores <- read.csv(
  file="../data/outcomes/hospital_value-based_purchasing__hvbp____total_performance_score.csv",
  header=TRUE,
  sep=",", 
  colClasses = c("character", "character", "character", "character", "character", "character", "character", "factor", "factor", "factor", "factor", "factor", "factor", "factor", "factor", "factor", "character"))
names(outcomes_performance_scores) <- gsub("\\.", "_", names(outcomes_performance_scores))

outcomes_efficiency_scores <- read.csv(
  file="../data/outcomes/hospital_value-based_purchasing__hvbp____efficiency_scores.csv",
  header=TRUE, sep=",",
  colClasses = c("character", "character", "character", "character", "character", "character", "character", "factor", "factor", "factor", "factor", "character", "character", "character", "character")
)
names(outcomes_performance_scores) <- gsub("\\.", "_", names(outcomes_performance_scores))


outcomes_readmissions_reductions <- read.csv(
  file="../data/outcomes/hospital_readmissions_reduction_program.csv",
  header=TRUE,
  sep=",", 
  colClasses = c("character", "character", "character", "character", "factor", "character", "factor", "factor", "factor", "factor", "Date")
)
names(outcomes_readmissions_reductions) <- gsub("\\.", "_", names(outcomes_readmissions_reductions))


# https://data.medicare.gov/Hospital-Compare/Hospital-Value-Based-Purchasing-HVBP-Clinical-Care/pudb-wetr
outcomes_clinical_care_domain_scores <- read.csv(
  file="../data/outcomes/hospital_value-based_purchasing__hvbp____clinical_care_domain_scores.csv",
  header=TRUE,
  sep=",",
  colClasses = c("character", "character", "character", "character", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character",
                 "character")
)
names(outcomes_clinical_care_domain_scores) <- gsub("\\.", "_", names(outcomes_clinical_care_domain_scores))

# https://data.medicare.gov/Hospital-Compare/Hospital-Acquired-Condition-Reduction-Program/yq43-i98g
outcomes_hac_reductions <- read.csv(
  file="../data/outcomes/hospital-acquired_condition_reduction_program.csv",
  header=TRUE,
  sep=",",
  colClasses = c("character", "character", "character", "character",
                 "factor", "character",
                 # TODO (Franklin): Parsing these dates returns errors so we're commenting it out
                 # "Date", "Date",
                 "character", "character",
                 "factor", "character",
                 "factor", "character",
                 "factor", "character",
                 "factor", "character",
                 "factor", "character",
                 "factor", "character",
                 "factor", "character",
                 # "Date", "Date",
                 "character", "character",
                 "factor", "character",
                 "character", "character")
)
names(outcomes_hac_reductions) <- gsub("\\.", "_", names(outcomes_hac_reductions))

# https://data.medicare.gov/Hospital-Compare/Hospital-ACS-Measures/akfs-5dgr
outcomes_acs_measures <- read.csv(
  file="../data/outcomes/hospital_acs_measures.csv",
  header=TRUE,
  sep=",",
  colClasses = c("character", "character", "character", "factor", "character",
                 "character", "factor", "character",
                 "character", "factor", "character")
)
names(outcomes_acs_measures) <- gsub("\\.", "_", names(outcomes_acs_measures))

# https://data.medicare.gov/Hospital-Compare/Hospital-Value-Based-Purchasing-HVBP-Patient-Exper/avtz-f2ge
outcomes_pt_experience_scores <- read.csv(
  file="../data/outcomes/patient_experience_of_care_domain_scores__hcahps_.csv",
  header=TRUE,
  sep=",",
  colClasses = c("character", "character", "character", "character", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "factor", "character", "character", "character",
                 "character")
)
names(outcomes_pt_experience_scores) <- gsub("\\.", "_", names(outcomes_pt_experience_scores))

# https://data.medicare.gov/Hospital-Compare/Hospital-Value-Based-Purchasing-HVBP-Safety/dgmq-aat3
outcomes_safety_scores <- read.csv(
  file="../data/outcomes/hospital_value-based_purchasing__hvbp____safety.csv",
  header=TRUE,
  sep=",",
  colClasses = c("character", "character", "character", "character", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character",
                 "factor", "factor", "factor", "factor", "character", "character", "character", "character")
)
names(outcomes_safety_scores) <- gsub("\\.", "_", names(outcomes_safety_scores))

# TODO (Franklin)
# https://data.medicare.gov/Hospital-Compare/Complications-and-Deaths-Hospital/ynj2-r877
outcomes_complications_and_deaths <- read.csv(
  file="../data/outcomes/complications_and_deaths_-_hospital.csv",
  header=TRUE,
  sep=","
  # colClasses = c("character", "character", "character", "character", "character", "character", "character",
  #               "character", "character", "character", "character", 
  #               "factor", "factor", "factor", "factor", "character",
  #               "Date", "Date", "character")
)
names(outcomes_complications_and_deaths) <- gsub("\\.", "_", names(outcomes_complications_and_deaths))

### Census Data
census_data <- read.csv(file="../data/census_data/ACS_17_5YR_DP03_with_ann.csv",
  header=TRUE,sep=",")

#Remove header row in row 1
census_data <- census_data[-1,]

#Fix names:
library(readxl)
library(dplyr)
names_census <- read_excel("../data/census_data/census_headers.xlsx")
names_census <- names_census[2,]
names_census <- as.character(names_census)

names(census_data) <- names_census
#View(census_data)
#important fields: 
census_data %>% select(geography, estimate_income_and_benefits_in_2017_inflation_adjusted_dollars_total_households_median_household_income_dollars, estimate_income_and_benefits_in_2017_inflation_adjusted_dollars_with_earnings_mean_earnings_dollars, estimate_income_and_benefits_in_2017_inflation_adjusted_dollars_with_social_security, estimate_income_and_benefits_in_2017_inflation_adjusted_dollars_with_retirement_income, estimate_income_and_benefits_in_2017_inflation_adjusted_dollars_with_retirement_income_mean_retirement_income_dollars,estimate_income_and_benefits_in_2017_inflation_adjusted_dollars_per_capita_income_dollars,estimate_health_insurance_coverage_civilian_noninstitutionalized_population, estimate_health_insurance_coverage_civilian_noninstitutionalized_population_with_health_insurance_coverage, estimate_health_insurance_coverage_civilian_noninstitutionalized_population_no_health_insurance_coverage,percent_percentage_of_families_and_people_whose_income_in_the_past_12_months_is_below_the_poverty_level_all_people) %>% View()

### Census Data - Population
census_data_pop <- read.csv(file="../data/census_data/PEP_2018_PEPANNRES_with_ann_populationestimates.csv",
  header=TRUE,sep=",")

census_pop_names <- c("id", "id2", "geography", "census_2010base", "est_base_2010", "census_2010", "census_2011", "census_2012", "census_2013", "census_2014", "census_2015", "census_2016", "census_2017", "census_2018")

names(census_data_pop) <- census_pop_names

census_data_pop <- census_data_pop[-1,]

# delete tables
dbRemoveTable(con, "hospital_info", hospital_info)
dbRemoveTable(con, "spending_by_claim", spending_by_claim)
dbRemoveTable(con, "spending_by_beneficiary", spending_by_beneficiary)
dbRemoveTable(con, "outcomes_performance_scores", outcomes_performance_scores)
dbRemoveTable(con, "outcomes_efficiency_scores", outcomes_efficiency_scores)
dbRemoveTable(con, "outcomes_readmissions_reductions", outcomes_readmissions_reductions)
dbRemoveTable(con, "outcomes_clinical_care_domain_scores", outcomes_clinical_care_domain_scores)
dbRemoveTable(con, "outcomes_hac_reductions", outcomes_hac_reductions)
dbRemoveTable(con, "outcomes_acs_measures", outcomes_acs_measures)
dbRemoveTable(con, "outcomes_pt_experience_scores", outcomes_pt_experience_scores)
dbRemoveTable(con, "outcomes_safety_scores", outcomes_safety_scores)
dbRemoveTable(con, "outcomes_complications_and_deaths", outcomes_complications_and_deaths)
dbRemoveTable(con, "census_data", census_data)
dbRemoveTable(con, "census_data_pop", census_data_pop)
# load tables
dbWriteTable(con, "hospital_info", hospital_info)
dbWriteTable(con, "spending_by_claim", spending_by_claim)
dbWriteTable(con, "spending_by_beneficiary", spending_by_beneficiary)
dbWriteTable(con, "outcomes_performance_scores", outcomes_performance_scores)
dbWriteTable(con, "outcomes_efficiency_scores", outcomes_efficiency_scores)
dbWriteTable(con, "outcomes_readmissions_reductions", outcomes_readmissions_reductions)
dbWriteTable(con, "outcomes_clinical_care_domain_scores", outcomes_clinical_care_domain_scores)
dbWriteTable(con, "outcomes_hac_reductions", outcomes_hac_reductions)
dbWriteTable(con, "outcomes_acs_measures", outcomes_acs_measures)
dbWriteTable(con, "outcomes_pt_experience_scores", outcomes_pt_experience_scores)
dbWriteTable(con, "outcomes_safety_scores", outcomes_safety_scores)
dbWriteTable(con, "outcomes_complications_and_deaths", outcomes_complications_and_deaths)
dbWriteTable(con, "census_data", census_data)
dbWriteTable(con, "census_data_pop", census_data_pop)


#Pull Data from DB
dbListTables(con)

# Disconnect from the database
dbDisconnect(con)

```
